apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: prometheus-example-app
  name: prometheus-example-app
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-example-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus-example-app
    spec:
      containers:
        - name: prometheus-example-app
#          image: quay.io/brancz/prometheus-example-app:v0.3.0
          # https://github.com/pavolloffay/prometheus-example-app/tree/native-histogram
#          image: pavolloffay/prometheus-example-no-histogram:1
          image: pavolloffay/prometheus-example:with-native-histogram-1
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus-example-app
  name: prometheus-example-app
  namespace: observability
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: web
  selector:
    app: prometheus-example-app
  type: ClusterIP
---
apiVersion: monitoring.rhobs/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: prometheus-example-monitor
  name: prometheus-example-monitor
  namespace: observability
spec:
  endpoints:
    - interval: 30s
      port: web
      scheme: http
  selector:
    matchLabels:
      app: prometheus-example-app
---
#apiVersion: monitoring.rhobs/v1
#kind: PodMonitor
#metadata:
#  labels:
#    app.kubernetes.io/name: prometheus-example-app
#  name: prometheus-example-app
#  namespace: observability
#spec:
#  selector:
#    matchLabels:
#      app.kubernetes.io/name: prometheus-example-app
#  podMetricsEndpoints:
#    - port: web