# https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/monitoring/configuring-core-platform-monitoring
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      remoteWrite:
     # - url: "http://otel-collector.observability.svc.cluster.local:9090/api/v1/write"
      - url: http://coo-monitoring-stack-prometheus.observability.svc.cluster.local:9090/api/v1/write
    # V2 does not work in the in-cluster monitoring
    #      protobuf_message: io.prometheus.write.v2.Request
