# based on config/samples/otelcol_v1alpha1_openshift.yaml
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: observability
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.137.0
  config:
    receivers:
      prometheusremotewrite:
        endpoint: 0.0.0.0:9090

    processors:

    exporters:
      debug:
        # basic, normal, detailed
        verbosity: normal
      prometheus:
        endpoint: "0.0.0.0:8889"
      otlphttp:
        endpoint: http://vendor-prometheus.observability.svc.cluster.local:9090/api/v1/otlp/
        tls:
          insecure: true


    service:
      telemetry:
        logs:
          level: "INFO"
          development: true
          encoding: "json"
        metrics:
      pipelines:
        metrics:
          receivers: [prometheusremotewrite]
          processors: []
          exporters:
            - debug
#            - otlphttp
