# Apply this manifest once the coo-monitoring-stack is deployed.
#  kubectl apply -f coo-prometheus.yaml --server-side
# this requires COO 1.3.0+
# https://github.com/prometheus-operator/prometheus-operator/blob/main/pkg/apis/monitoring/v1/prometheus_types.go#L755
apiVersion: monitoring.rhobs/v1
kind: Prometheus
metadata:
  name: coo-monitoring-stack
spec:
#  image: prom/prometheus:v3.7.0
  # https://github.com/rhobs/observability-operator/pull/906#pullrequestreview-3344554594
  # likely to make to COO 1.3.0
  # Prom operator 0.86.1 deploys Prometheus 3.6.0
  image: prom/prometheus:v3.6.0
  convertClassicHistogramsToNHCB: true
  additionalArgs:
    - name: web.enable-remote-write-receiver
  enableFeatures:
    - metadata-wal-records
    - native-histograms