# Apply this manifest once the coo-monitoring-stack is deployed.
#  kubectl apply -f coo-prometheus.yaml --server-side
apiVersion: monitoring.rhobs/v1
kind: Prometheus
metadata:
  name: coo-monitoring-stack
spec:
  enableFeatures:
    - metadata-wal-records
    - native-histograms