apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: coo-monitoring-stack
  namespace: observability
spec:
  logLevel: debug
  retention: 7d
  resourceSelector:
    matchLabels:
      app: observability
  alertmanagerConfig:
    disabled: true
  prometheusConfig:
    replicas: 1
    enableOtlpHttpReceiver: true
    remoteWrite:
    - url: http://otel-collector.observability.svc.cluster.local:9090/api/v1/write
      messageVersion: V2.0
      sendExemplars: true
      sendNativeHistograms: true