apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: logging
  namespace: openshift-logging
spec:
  managementState: Managed
  outputs:
    - lokiStack:
        authentication:
          token:
            from: serviceAccount
        target:
          name: logging-loki
          namespace: openshift-logging
      tls:
        ca:
          configMapName: openshift-service-ca.crt
          key: service-ca.crt
      name: logging-loki
      type: lokiStack
  pipelines:
    - inputRefs:
        - application
        - infrastructure
      outputRefs:
        - logging-loki
      name: logs-to-loki
  serviceAccount:
    name: log-collector