apiVersion: v1
kind: Secret
metadata:
  name: minio-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  minio.yaml: |
    type: s3
    config:
      bucket: "tempo"
      endpoint: "minio:9000"
      insecure: true
      access_key: "tempo"
      secret_key: "supersecret"
---
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  namespace: open-cluster-management-observability
spec:
  advanced:
    observatoriumAPI:
      replicas: 1
    queryFrontend:
      replicas: 1
    query:
      replicas: 1
    receive:
      replicas: 1
    rule:
      replicas: 1
    store:
      replicas: 1
    storeMemcached:
      replicas: 1
    queryFrontendMemcached:
      replicas: 1
    alertmanager:
      replicas: 1
    rbacQueryProxy:
      replicas: 1
    grafana:
      replicas: 1
  observabilityAddonSpec: {}
  storageConfig:
    metricObjectStorage:
      name: minio-object-storage
      key: minio.yaml