apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: open-cluster-management-observability
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: otel-serving-cert
spec:
  mode: deployment
  replicas: 1
  volumes:
    - name: mco-ca
      secret:
        secretName: observability-managed-cluster-certs
    - name: mco-certs
      secret:
        secretName: observability-controller-open-cluster-management.io-observability-signer-client-cert
    - name: otel-certs
      secret:
        secretName: otel-serving-cert
  volumeMounts:
    - name: mco-ca
      mountPath: /etc/mco/ca
    - name: mco-certs
      mountPath: /etc/mco/certs
    - name: otel-certs
      mountPath: /etc/otel/certs
  config:
    exporters:
      debug:
        verbosity: detailed
      prometheusremotewrite:
        endpoint: https://observatorium-api-open-cluster-management-observability.apps.demo.ecoeng-flightctl.devcluster.openshift.com/api/metrics/v1/default/api/v1/receive
        tls:
          cert_file: /etc/mco/certs/tls.crt
          key_file: /etc/mco/certs/tls.key
          ca_file: /etc/mco/ca/ca.crt
        resource_to_telemetry_conversion:
          enabled: true
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 25
      resource:
        attributes:
          - key: source
            value: rhde
            action: insert
          # fix "Permanent error: Permanent error: Permanent error: remote write returned HTTP status 409 Conflict; err = %!w(<nil>): add 1377 series: label set contains a label with empty name or value
          - key: process.executable.path
            action: delete
          - key: process.command
            action: delete
          - key: process.command_line
            action: delete
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              cert_file: /etc/otel/certs/tls.crt
              key_file: /etc/otel/certs/tls.key
    service:
      pipelines:
        metrics:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - resource
            - batch
          exporters:
            - debug
            - prometheusremotewrite
